import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "FoodPal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={inter.className}>

      <head>
        <link rel="icon" href="/FoodPalLogo.png" type="image/png"/>
        <title>FoodPal</title>

      </head>
        {children}
        </body>
    </html>
  );
}
